plugins {
    alias libs.plugins.architectury.noremap apply false
    alias libs.plugins.architectury.remap apply false
    alias libs.plugins.preprocessor
}

preprocess {
    strictExtraMappings = true

    var mc11605_forge = createNode("1.16.5-forge", 1_16_05, 'mojang')
    var mc11701_forge = createNode("1.17.1-forge", 1_17_01, 'mojang')
    var mc11802_forge = createNode("1.18.2-forge", 1_18_02, 'mojang')
    var mc11902_forge = createNode("1.19.2-forge", 1_19_02, 'mojang')
    var mc11904_forge = createNode("1.19.4-forge", 1_19_04, 'mojang')
    var mc12001_forge = createNode("1.20.1-forge", 1_20_01, 'mojang')
    var mc12002_forge = createNode("1.20.2-forge", 1_20_02, 'mojang')

    mc11605_forge.link(mc11701_forge, null)
    mc11701_forge.link(mc11802_forge, file("versions/1.17.1-map2-1.18.2"))
    mc11802_forge.link(mc11902_forge, file("versions/1.18.2-map2-1.19.2"))
    mc11902_forge.link(mc11904_forge, file("versions/1.19.2-map2-1.19.4"))
    mc11904_forge.link(mc12001_forge, null)
    mc12001_forge.link(mc12002_forge, null)

    var mc12002_neoforge = createNode("1.20.2-neoforge", 1_20_02, 'mojang')
    var mc12004_neoforge = createNode("1.20.4-neoforge", 1_20_04, 'mojang')
    var mc12006_neoforge = createNode("1.20.6-neoforge", 1_20_06, 'mojang')
    var mc12101_neoforge = createNode("1.21.1-neoforge", 1_21_01, 'mojang')
    var mc12104_neoforge = createNode("1.21.4-neoforge", 1_21_04, 'mojang')
    var mc12108_neoforge = createNode("1.21.8-neoforge", 1_21_08, 'mojang')
    var mc260102_neoforge = createNode("26.1.2-neoforge", 26_01_02, 'mojang')
    var mc260200_neoforge = createNode("26.2-neoforge", 26_02_00, 'mojang')

    mc12002_forge.link(mc12002_neoforge, file("versions/forge-map2-neoforge"))
    mc12002_neoforge.link(mc12004_neoforge, null)
    mc12004_neoforge.link(mc12006_neoforge, null)
    mc12006_neoforge.link(mc12101_neoforge, file("versions/1.20.6-map2-1.21.1"))
    mc12101_neoforge.link(mc12104_neoforge, null)
    mc12104_neoforge.link(mc12108_neoforge, null)
    mc12108_neoforge.link(mc260102_neoforge, null)
    mc260102_neoforge.link(mc260200_neoforge, null)

    for (final def node in getNodes()) {
        findProject(node.project).ext.mcVersion = node.mcVersion
        var modPlatform = "none"
        if (node.project.endsWith("-fabric")) {
            modPlatform = "fabric"
        } else if (node.project.endsWith("-forge")) {
            modPlatform = "forge"
        } else if (node.project.endsWith("-neoforge")) {
            modPlatform = "neoforge"
        }
        findProject(node.project).ext.modPlatform = modPlatform
    }
}

ext {
    Map env = System.getenv()
    File localPropsFile = file("${rootDir}/local.properties")

    if (localPropsFile.exists()) {
        Properties p = new Properties()
        p.load(new FileInputStream(localPropsFile))
        p.each { key, value ->
            ext[key as String] = value
        }
    }

    getEnv = {
        return env
    }

    getOrDefault = { String key, String defaultValue ->
        String value
        (value = project.findProperty(key)) && !value.isEmpty() ? value : defaultValue
    }

    getVersionSuffix = {
        String number = env.GITHUB_RUN_NUMBER ? env.GITHUB_RUN_NUMBER : 'x'
        String type = env.VERSION_TYPE
        switch (type) {
            case 'release': return ''
            case 'beta': return "+snapshot.${number}"
            case 'alpha': return "+pr.${number}"
            default: return "+build.${number}"
        }
    }

    getVersion = { Project proj ->
        return "${proj.property("mod.version")}${getVersionSuffix()}"
    }
}

tasks.register("genLocalProperties") {
    it.group("${project.property("mod.id")}")

    doFirst {
        File localPropsFile = file("${rootDir}/local.properties")

        if (localPropsFile.exists()) {
            throw new IllegalStateException("local.properties file already generated. If you want to regenerate it, please delete it manually first")
        } else {
            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(localPropsFile))
            bufferedWriter.writeLine("# Build environment configurations")
            bufferedWriter.writeLine("ow.build.environment.local=")
            bufferedWriter.writeLine("ow.build.environment.buildType=")
            bufferedWriter.writeLine("ow.game.window.width=")
            bufferedWriter.writeLine("ow.game.window.height=")
            bufferedWriter.writeLine("ow.game.window.username=")
            bufferedWriter.close()

            project.getLogger().info("local.properties generated successfully!")
        }
    }
}

tasks.register("cleanPreprocessSources") {
    it.group("${project.mod_id}")

    doFirst {
        subprojects {
            def path = project.projectDir.toPath().resolve("build/preprocessed")
            path.toFile().deleteDir()
        }
    }
}

tasks.register("copyAllJars", Copy) {
    var libs = it.rootSpec.addChild()
    var devlibs = it.rootSpec.addChild()
    subprojects.forEach { subproject ->
        libs.from(subproject.layout.buildDirectory.dir("libs")) {
            include("*.jar")
        }
        devlibs.from(subproject.layout.buildDirectory.dir("devlibs")) {
            include("*.jar")
        }
    }
    doFirst {
        delete layout.buildDirectory.dir("libs")
        delete layout.buildDirectory.dir("devlibs")
    }
    into(layout.buildDirectory)
    libs.into("libs")
    devlibs.into("devlibs")
    it.with(libs, devlibs)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
