org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Mod Properties
mod.id=nieih
mod.name=NoInfiniteEffectsInHud
mod.description=Disables infinite effects display in the hud
mod.homepage=https://github.com/QiuShui1012/NoInfiniteEffectsInHud
mod.license=GNU AGPL 3.0
mod.maven_group=com.qiushui1012.mod
mod.authors=QiuShui1012
mod.sources=https://github.com/QiuShui1012/NoInfiniteEffectsInHud
mod.version=3.0.0
mod.archives_base_name=nieih
