modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"
issueTrackerURL="${mod_sources}/issues"
clientSideOnly=true

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
logoFile="icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="${mod_id}.mixins.json"
