plugins {
    id 'java'
    id 'io.freefair.lombok' version '9.2.0'
}

final int mcVersion = project.mcVersion
final String modPlatform = project.modPlatform

apply plugin: 'dev.architectury.loom-no-remap'
apply plugin: "com.replaymod.preprocess"

preprocess {
    vars.put("MC", mcVersion)
    vars.put("JAVA", java.sourceCompatibility.ordinal() + 1)
    vars.put("FORGE", 0)
    vars.put("NEOFORGE", modPlatform == "neoforge" ? 1 : 0)

    patternAnnotation = "com.qiushui1012.mod.nieih.util.Pattern"
}

loom.silentMojangMappingsLicense()

repositories {
    mavenLocal()

    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases"
    }

    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.property("dependencies.minecraft_version")}"
    neoForge "net.neoforged:neoforge:${project.property("dependencies.neoforge_version")}"
}

loom {
    enableTransitiveAccessWideners = false

    interfaceInjection {
        enableDependencyInterfaceInjection = false
        isEnabled = false
    }

    var isJbr = System.getProperty('java.vm.vendor').contains('JetBrains')
    runs {
        client {
            systemProperties.put "--username", project.getOrDefault("ow.game.window.username", "dev")
            runDirectory = file("runs/client")
        }

        server {
            runDirectory = file("runs/server")
        }

        configureEach {
            // Dump modified classes automatically.
            systemProperties.put "mixin.debug.export", "true"
            systemProperties.put "sun-misc-unsafe-memory-access", "allow"
            if (isJbr) jvmArguments.add "-XX:+AllowEnhancedClassRedefinition"
        }
    }

}

base {
    archivesName = "${project.parent.property("mod.archives_base_name")}-${project.property("dependencies.minecraft_version")}-${modPlatform}"
    group = "${project.property("mod.maven_group")}"
    version = project.getVersion(project.parent)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

processResources {
    inputs.property("minecraft_dependency", project.property("dependencies.minecraft_dependency"))
    inputs.property("mod_id", project.parent.property("mod.id"))
    inputs.property("mod_name", project.parent.property("mod.name"))
    inputs.property("mod_description", project.parent.property("mod.description"))
    inputs.property("mod_homepage", project.parent.property("mod.homepage"))
    inputs.property("mod_license", project.parent.property("mod.license"))
    inputs.property("mod_authors", project.parent.property("mod.authors"))
    inputs.property("mod_sources", project.parent.property("mod.sources"))
    inputs.property("mod_version", project.getVersion(this.project.parent))
    inputs.property("java_version", java.sourceCompatibility.getMajorVersion())

    filesMatching(["META-INF", "META-INF/neoforge.mods.toml", "nieih.mixins.json"]) {
        expand([
            "minecraft_dependency" : inputs.properties.get("minecraft_dependency"),
            "mod_id"               : inputs.properties.get("mod_id"),
            "mod_name"             : inputs.properties.get("mod_name"),
            "mod_description"      : inputs.properties.get("mod_description"),
            "mod_homepage"         : inputs.properties.get("mod_homepage"),
            "mod_license"          : inputs.properties.get("mod_license"),
            "mod_authors"          : inputs.properties.get("mod_authors"),
            "mod_sources"          : inputs.properties.get("mod_sources"),
            "mod_version"          : inputs.properties.get("mod_version"),
            "java_version"         : inputs.properties.get("java_version")
        ])
    }

    from "${rootDir}/LICENSE"
    exclude "com/qiushui1012/mod/nieih/integration/compositematerial/CMCompat.class"
    exclude "com/qiushui1012/mod/nieih/mixin/InventoryAccessor.class"
    exclude "com/qiushui1012/mod/nieih/mixin/GuiMixin.class"
}

tasks.named('sourcesJar').configure {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from delombok.outputs.files
    dependsOn delombok
}

tasks.named("runClient").configure {
    dependsOn tasks.named("build")
}

artifacts {
    archives tasks.sourcesJar
}

// Setup server default settings.
tasks.named("runServer") {
    defaultCharacterEncoding = "UTF-8"

    doFirst {
        // Agree eula before server init.
        file("${project.projectDir}/run/server/eula.txt").with { File f -> {
            if (!f.exists()) {
                f.parentFile.mkdirs()
                f.withWriter { BufferedWriter writer ->
                    writer.writeLine("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).")
                    writer.writeLine("#${new Date()}")
                    writer.writeLine("eula=true")
                }
            }
        }}
    }
}

tasks.register("cleanRuns", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDirectory).parentFile.deleteDir()
    }
}

tasks.register("cleanRunClient", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDirectory).deleteDir()
    }
}

tasks.register("cleanRunServer", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.server.runDirectory).deleteDir()
    }
}

[
    "cleanRuns", "cleanRunClient", "cleanRunServer",
    "runClient", "runServer",
    "preprocessCode", "preprocessResources",
    "preprocessTestCode", "preprocessTestResources"
].forEach { taskName ->
    if (tasks.getNames().contains(taskName)) {
        tasks.named(taskName) {
            it.group = "${project.property("mod.id")}"
        }
    }
}

lombok.version = "1.18.46"
