name: CI for Nieih
on:
  workflow_dispatch:
  push:
    branches:
      - release/**
    paths:
      - .github/workflows/ci.yml
      - src/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_BUILD: true
      PR_BUILD: false
    permissions:
       contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name mod_version loader_id loader_name java_version'

      - name: Setup Java ${{ steps.properties.outputs.java_version }}
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: ${{ steps.properties.outputs.java_version }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Build
        run: ./gradlew build

      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | awk -F '${{ steps.properties.outputs.mod_id }}-${{ steps.properties.outputs.loader_id }}-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> "$GITHUB_OUTPUT"

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.properties.outputs.loader_name }} ${{ steps.version.outputs.version }}"
          path: build/libs/

      - name: gametest
        uses: Anvil-Dev/dedicated-server-launch-test@1.21.1-neoforge
        with:
          mod: build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.properties.outputs.loader_id }}-${{ steps.version.outputs.version }}.jar

      - name: Publish to Mod Platforms
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.properties.outputs.mod_version }}"
          version: "all-${{ steps.properties.outputs.loader_id }}-${{ steps.properties.outputs.mod_version }}"
          version-type: release
          java: ${{ steps.properties.outputs.java_version }}
          files: |
            build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.properties.outputs.loader_id }}-${{ steps.version.outputs.version }}.jar
            build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.properties.outputs.loader_id }}-${{ steps.version.outputs.version }}-sources.jar

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-dependencies: |
            982540(optional)
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-commitish: "release/all-${{ steps.properties.outputs.loader_id }}-${{ steps.properties.outputs.mod_version }}"
          github-tag: "all-${{ steps.properties.outputs.loader_id }}-${{ steps.properties.outputs.mod_version }}"
          github-token: ${{ secrets.GIT_TOKEN }}
